#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP grouped_sum_rle1(SEXP, SEXP, SEXP, SEXP);
extern SEXP grouped_sum1(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"grouped_sum_rle1", (DL_FUNC) &grouped_sum_rle1, 4},
    {"grouped_sum1",     (DL_FUNC) &grouped_sum1,     3},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_grouperise(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
